// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddBeneficiaryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void checkifselfaccountnocanbeaddedinbeneficiarytable() {
    driver.get("http://localhost:8097/OnlineBankingApplication/BeneficiaryDetails.jsp");
    driver.findElement(By.id("beneficiaryAccountNo")).sendKeys("2700001");
    driver.findElement(By.id("beneficiaryName")).sendKeys("Vini");
    driver.findElement(By.id("IFSCCode")).sendKeys("SDDS0SDDSSD");
    driver.findElement(By.id("branchName")).sendKeys("Bund Garden");
    driver.findElement(By.id("bankName")).sendKeys("Bank of India");
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
  @Test
  public void checkifsccodeformataddbeneficiary() {
    driver.get("http://localhost:8097/OnlineBankingApplication/BeneficiaryDetails.jsp");
    driver.findElement(By.id("beneficiaryAccountNo")).sendKeys("2700001");
    driver.findElement(By.id("beneficiaryName")).sendKeys("Vini");
    driver.findElement(By.id("IFSCCode")).sendKeys("sffsfs");
    driver.findElement(By.id("branchName")).sendKeys("Bund Garden");
    driver.findElement(By.id("bankName")).sendKeys("Bank of India");
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
