// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ForgotPasswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void correctForgotpasswordprocess() {
    // Test name: Correct Forgot password process
    // Step # | name | target | value
    // 1 | open | LoginPage.jsp | 
    driver.get("http://localhost:8097/OnlineBankingApplication/LoginPage.jsp");
    // 2 | click | linkText=Forgot your password? | 
    driver.findElement(By.linkText("Forgot your password?")).click();
    // 3 | click | css=span | 
    driver.findElement(By.cssSelector("span")).click();
    // 4 | type | name=emailId | shivani.taru201@gmail.com
    driver.findElement(By.name("emailId")).sendKeys("shivani.taru201@gmail.com");
    // 5 | click | css=.btn-lg | 
    driver.findElement(By.cssSelector(".btn-lg")).click();
    // 6 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 7 | open | ResetPassword.jsp | 
    driver.get("http://localhost:8097/OnlineBankingApplication/ResetPassword.jsp");
    // 8 | type | id=password | Vini1234
    driver.findElement(By.id("password")).sendKeys("Vini1234");
    // 9 | type | id=confirmPassword | Vini1234
    driver.findElement(By.id("confirmPassword")).sendKeys("Vini1234");
    // 10 | click | css=.btn-success | 
    driver.findElement(By.cssSelector(".btn-success")).click();
    // 11 | type | name=uname | shivani.taru201@gmail.com
    driver.findElement(By.name("uname")).sendKeys("shivani.taru201@gmail.com");
    // 12 | type | name=pass | Vini1234
    driver.findElement(By.name("pass")).sendKeys("Vini1234");
    // 13 | sendKeys | name=pass | ${KEY_ENTER}
    driver.findElement(By.name("pass")).sendKeys(Keys.ENTER);
  }
  @Test
  public void invalidEmailId() {
    // Test name: Invalid Email Id
    // Step # | name | target | value
    // 1 | open | LoginPage.jsp | 
    driver.get("http://localhost:8097/OnlineBankingApplication/LoginPage.jsp");
    // 2 | click | linkText=Forgot your password? | 
    driver.findElement(By.linkText("Forgot your password?")).click();
    // 3 | click | css=span | 
    driver.findElement(By.cssSelector("span")).click();
    // 4 | click | name=emailId | 
    driver.findElement(By.name("emailId")).click();
    // 5 | type | name=emailId | abc@gmail.com
    driver.findElement(By.name("emailId")).sendKeys("abc@gmail.com");
    // 6 | click | css=.btn-lg | 
    driver.findElement(By.cssSelector(".btn-lg")).click();
  }
}
